### ISSUE TITLE
Malformed Slack Message & NPM Release

### ISSUE THREAD

**Issue by mattrmiller** [schibsted/serverless-slack-deploy-notification#8]
The following message does not close a bold, resulting in the siren emoji not to be rendered:

`*${this.service.service}* ${deployer} triggered *${this.stage}* deployment :siren:`

should be:

`*${this.service.service}* ${deployer}* triggered *${this.stage}* deployment :siren:`

Also it looks like v0.3.2 never got published to NPM, we are hitting the 3000 character limit in Slack.

**Comment by domeq** [comment]
So sorry for missing this issue - somehow slipped through my notifications.
I've fixed the release process, so new version is out on NPM already.

I don't see how the first message is malformed now, aren't you suggesting adding an unopened `*` after `deployer`?
Maybe you have a `*` in the service name or deployer and this makes the message malformed? In that case it might make sense to strip markdown chars from these variables.
